WITH TOTAL_CAR AS (
    SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (1-C.DISCOUNT_RATE/100) * (30),0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN (
        SELECT CAR_ID, END_DATE 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30' 
    ) AS B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN (
        SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE CAST(REGEXP_SUBSTR(DURATION_TYPE, '[0-9]+') AS UNSIGNED) = 30
    ) AS C ON A.CAR_TYPE = C.CAR_TYPE 
    WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV' ) AND B.CAR_ID IS NULL
    ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
)
SELECT *
FROM TOTAL_CAR
WHERE FEE >= 500000 AND FEE < 2000000;