-- 코드를 입력하세요
SELECT ANIMAL_ID,ANIMAL_TYPE, NAME 
FROM ANIMAL_INS 
WHERE SUBSTRING_INDEX(SEX_UPON_INTAKE, ' ', 1) = 'Intact' AND ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE (SUBSTRING_INDEX(SEX_UPON_OUTCOME, ' ', 1) IN ('Spayed','Neutered')))