WITH RECURSIVE ECOLI AS(
SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
SELECT A.ID, A.PARENT_ID, ECOLI.GENERATION +1
    FROM ECOLI JOIN ECOLI_DATA A 
    ON ECOLI.ID = A.PARENT_ID   
    )
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI
WHERE ID NOT IN (SELECT PARENT_ID 
                  FROM ECOLI
                  WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION;