SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.SUM_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (SELECT PRODUCT_ID,SUM(AMOUNT) AS SUM_AMOUNT,PRODUCE_DATE FROM FOOD_ORDER WHERE MONTH(PRODUCE_DATE)=5
     GROUP BY PRODUCT_ID) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;