WITH TOTAL AS(
    SELECT A.FLAVOR,(A.NODUPL_ORDER+B.NODUPL_ORDER) AS TOTAL_ORDER
    FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS NODUPL_ORDER FROM FIRST_HALF GROUP BY FLAVOR) AS A JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS NODUPL_ORDER FROM JULY GROUP BY FLAVOR) AS B ON A.FLAVOR = B.FLAVOR
)

SELECT FLAVOR
FROM TOTAL
ORDER BY TOTAL_ORDER DESC
LIMIT 3;