WITH FilteredCars AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) > 4
)
SELECT 
    MONTH(B.START_DATE) AS MONTH, 
    B.CAR_ID, 
    COUNT(B.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
JOIN FilteredCars F ON B.CAR_ID = F.CAR_ID 
WHERE B.START_DATE >= '2022-08-01' AND B.START_DATE < '2022-11-01'
GROUP BY MONTH(B.START_DATE), B.CAR_ID
HAVING RECORDS>0
ORDER BY MONTH(B.START_DATE), B.CAR_ID DESC;